INSERT INTO suppliers (name, email, phone, address)
VALUES
('A2','','',''),
('ARRA','','',''),
('Arravite','','',''),
('BAYER','','',''),
('BEROCCA','','',''),
('BG','','',''),
('BIOISLAND','','',''),
('BIOSTIME','','',''),
('BLACKMORES','','',''),
('CANESTEN','','',''),
('CVS','','',''),
('DEVONDALE','','',''),
('DUIT','','',''),
('EAORON','','',''),
('FB','','',''),
('G&M','','',''),
('HEALTHY CARE','','',''),
('HOPES','','',''),
('LIFESPACE','','',''),
('LUCAS','','',''),
('MAXIGENES','','',''),
('NATURES OWN','','',''),
('NP','','',''),
('NW','','',''),
('OSTELIN','','',''),
('PROCTOSEDYL','','',''),
('QV','','',''),
('REDWIN','','',''),
('SAMBUCOL','','',''),
('SANOFI','','',''),
('SELSUN','','',''),
('Sukin','','',''),
('SUNSENSE','','',''),
('SWISSE','','',''),
('THOMPSONS','','',''),
('THURSDAY','','',''),
('VIERRA','','','')
;

INSERT INTO brands (code, name, supplier_id)
VALUES
('','A2','')
('','Arravite','')
('','BAYER','')
('','BEROCCA','')
('','BG','')
('','BIOISLAND','')
('','BIOSTIME','')
('','BLACKMORES','')
('','CANESTEN','')
('','CVS','')
('','DERMATIX','')
('','DEVONDALE','')
('','DUIT','')
('','EAORON','')
('','FB','')
('','G&M','')
('','HEALTHY CARE','')
('','HOPES','')
('','LIFESPACE','')
('','LUCAS','')
('','MAXIGENES','')
('','NATURES OWN','')
('','NP','')
('','NW','')
('','OSTELIN','')
('','PROCTOSEDYL','')
('','QV','')
('','REDWIN','')
('','SAMBUCOL','')
('','SELSUN','')
('','Sukin','')
('','SUNSENSE','')
('','SWISSE','')
('','THOMPSONS','')
('','THURSDAY','')
('','VIERRA','')
;